name: Nightly Kernel Build

# Schedule the workflow to run every day at midnight UTC
# on:
#   schedule:
#     - cron: "0 0 * * *"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the kernel source code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up a Linux environment with necessary dependencies
      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install git fakeroot ccache build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison python3 python-is-python3 -y

      - name: Download KernelSU
        run: |
          git submodule update --init --recursive

      - name: Download toolchain
        run: |
          sudo git clone --depth=1 https://github.com/kdrag0n/proton-clang ~/toolchains/proton-clang/

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export PLATFORM_VERSION=12
          export ANDROID_MAJOR_VERSION=s
          export LLVM=1
          export LLVM_IAS=1        
          export PATH=/home/runner/toolchains/proton-clang/bin/:$PATH
          make kawa_defconfig CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-

      # Optionally, you can upload the compiled kernel as an artifact
      - name: Upload Kernel Build
        uses: actions/upload-artifact@v3
        with:
          name: kernel-build
          path: ./arch/arm64/boot/Image  # Path to the built kernel image
